apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-diamond-
spec:
  entrypoint: diamond
  templates:
  - name: run-and-sleep
    inputs:
      parameters:
      - name: message
      - name: sleeptime
    container:
      imagePullPolicy: Always
      image: balchu/run-and-sleep:1.0
      command: [run.sh]
      args: ["{{inputs.parameters.message}}","{{inputs.parameters.sleeptime}}"]
  - name: fail-job
    inputs:
      parameters:
      - name: message
      - name: sleeptime
    container:
      image: balchu/run-and-fail:1.1
      command: [run-with-failure.sh]
      args: ["{{inputs.parameters.message}}","{{inputs.parameters.sleeptime}}"]

  - name: diamond
    dag:
      tasks:
      - name: Task-A-and-sleep-for-5s
        template: run-and-sleep
        arguments:
          parameters:
          - name: message
            value: "task1"
          - name: sleeptime
            value: "5"
      - name: Task-B-and-sleep-for-20s
        dependencies: [Task-A-and-sleep-for-5s]
        template: run-and-sleep
        arguments:
          parameters:
          - name: message
            value: "task1"
          - name: sleeptime
            value: "20"
      - name: Task-C
        dependencies: [Task-A-and-sleep-for-5s]
        template: fail-job
        arguments:
          parameters:
          - name: message
            value: "task1"
          - name: sleeptime
            value: "50"

      - name: Task-D
        dependencies: [Task-B-and-sleep-for-20s, Task-C]
        template: run-and-sleep
        arguments:
          parameters:
          - name: message
            value: "task1"
          - name: sleeptime
            value: "10"
